export const LOAD_TASKS_FAILED = "LOAD_TASKS_FAILED";
export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const SUBMIT_NEW_TASK = "SUBMIT_NEW_TASK";
export const TOGGLE_TASK_SUCCESS = "TOGGLE_TASK_SUCCESS";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILED = "USER_FAILED";
export const API_FAILED = "API_FAILED";
export const API_SUCCEED = "API_SUCCEED";
